### ISSUE TITLE
Fix documentation on save method

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-db#30] opened 2015-07-28 05:46 UTC
I lost hours trying to figure just how to save a document. Documentation says `save` will create or update the object, but I get `not_found: missing` errors in the logs when I try to use it to create a new object.
Also documentation says that `save` should return the updated object. That's not true.

**Comment by aenario** [comment] 2015-07-28 07:17
duplicate of https://github.com/cozy/cozy-db/issues/24

**Closed as completed** 2016-08-11 14:43 UTC
Labels: duplicate
